/**
 * Gravitee.io Portal Rest API
 * API dedicated to the devportal part of Gravitee
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: contact@graviteesource.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Map of Permissions.
 */
export interface UserPermissions { 
    INSTANCE?: Array<string>;
    GROUP?: Array<string>;
    TAG?: Array<string>;
    TENANT?: Array<string>;
    API?: Array<string>;
    APPLICATION?: Array<string>;
    PLATFORM?: Array<string>;
    AUDIT?: Array<string>;
    NOTIFICATION?: Array<string>;
    MESSAGE?: Array<string>;
    DICTIONARY?: Array<string>;
    ALERT?: Array<string>;
    ENTRYPOINT?: Array<string>;
    SETTINGS?: Array<string>;
    QUALITY_RULE?: Array<string>;
    DASHBOARD?: Array<string>;
    METADATA?: Array<string>;
    DOCUMENTATION?: Array<string>;
    CATEGORY?: Array<string>;
    TOP_APIS?: Array<string>;
    API_HEADER?: Array<string>;
    IDENTITY_PROVIDER?: Array<string>;
    CLIENT_REGISTRATION_PROVIDER?: Array<string>;
    THEME?: Array<string>;
}

